# Site settings
class:
  short: SAVI-800
  long: Advanced Interactive Web Mapping
  term: Spring 2016
school:
  name: Pratt SAVI
  link: https://www.pratt.edu/pratt-research-and-centers/spatial-analysis-visualization-initiative/
email:
description: > # this means to ignore newlines until "baseurl:"
  DESCRIPTION
baseurl: /spring2016/
url: http://pratt-savi-800.github.io
twitter_username: PrattSAVI
github_username: pratt-savi

# Build settings
markdown: kramdown

# Collections
collections:
  projects:
    author: name
    output: true
    permalink: /projects/:path/
